name       : linux-driver-management
version    : 0.1.0
release    : 3
source     :
    - https://github.com/solus-project/linux-driver-management/releases/download/v0.1.0/linux-driver-management-0.1.0.tar.xz : 3ee39bbf9effc88531c8d335358fcee2cb45694471bec4ddf6220e4f9e2b10c4
license    : LGPL-2.1
component  : system.utils
summary    : Linux Driver Management
replaces   : gl-driver-switch
builddeps  :
    - pkgconfig(libpci)
description: |
    Linux Driver Management (LDM) provides the core functionality required for integration of drivers into modern Linux distributions. It provides centralised tooling for detection and configuration for drivers, with a specific focus currently on display drivers.
setup      : |
    %meson_configure -Dwith-gl-driver-switch-compat=true
build      : |
    %meson_build
install    : |
    %meson_install 
