name       : linux-driver-management
version    : 1.0.3
release    : 15
source     :
    - https://github.com/solus-project/linux-driver-management/releases/download/v1.0.3/linux-driver-management-1.0.3.tar.xz : 968ef61fbb7e26b89ef9456f03cf31c616bdc8fc69531fcfd9f90ae0f4ff147b
license    : LGPL-2.1
component  :
    - system.base
    - gdm-integration : desktop.gnome
    - lightdm-integration : desktop.lightdm
    - sddm-integration : desktop
summary    :
    - Linux Driver Management
    - gdm-integration : LDM Integration for GDM
    - lightdm-integration : LDM Integration for LightDM
    - sddm-integration : LDM Integration for SDDM
description: |
    Linux Driver Management (LDM) provides the core functionality required for integration of drivers into modern Linux distributions. It provides centralised tooling for detection and configuration for drivers, with a specific focus currently on display drivers.
replaces   : gl-driver-switch
builddeps  :
    - pkgconfig(check)
    - pkgconfig(gio-unix-2.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(libkmod)
    - pkgconfig(libudev)
    - pkgconfig(libusb-1.0)
    - pkgconfig(umockdev-1.0)
    - pkgconfig(xorg-server)
    - vala
patterns   :
    - gdm-integration :
        - /usr/share/gdm/greeter/autostart/ldm-session-init.desktop
        - /usr/share/xdg/autostart/ldm-session-init.desktop
    - lightdm-integration :
        - /usr/share/lightdm/lightdm.conf.d/99-ldm.conf
    - sddm-integration :
        - /usr/share/sddm/scripts/Xsetup
setup      : |
    %meson_configure -Dwith-gl-driver-switch-compat=true \
                     -Dwith-autostart-dir=/usr/share/xdg/autostart
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
