name       : linux-driver-management
version    : 0.0.2
release    : 2
source     :
    - https://github.com/solus-project/linux-driver-management/archive/v0.0.2.tar.gz : d4278a0ad959b723f49ec0f736262677da55be4044c0e042c67791a753888fa6
license    : LGPL-2.1
component  : system.utils
summary    : Linux Driver Management
replaces   : gl-driver-switch
builddeps  :
    - pkgconfig(libpci)
    - meson
description: |
    Linux Driver Management (LDM) provides the core functionality required for integration of drivers into modern Linux distributions. It provides centralised tooling for detection and configuration for drivers, with a specific focus currently on display drivers.
setup      : |
    %meson_configure -Dwith-gl-driver-switch-compat=true build
build      : |
    %meson_build -C build
install    : |
    %meson_install -C build
